import 'package:firebase_core/firebase_core.dart';

class FirebaseOptionsProvider {
  static FirebaseOptions get currentPlatform {
    // This is a stub for FirebaseOptions. In a real project,
    // this would be generated by flutterfire configure.
    return const FirebaseOptions(
      apiKey: 'dummy-api-key',
      appId: 'dummy-app-id',
      messagingSenderId: 'dummy-sender-id',
      projectId: 'dummy-project-id',
    );
  }
}
